### ISSUE TITLE
Task resolveDependencies takes too long

### ISSUE THREAD

**Issue by gaelcolas** [gaelcolas/SampleModule#1]
This is a problem because it's the first to run, and even when everything is set up, it still takes some time to lookup for updated modules. 
Maybe pinning version is quicker?

**Comment by RamblingCookieMonster** [comment]
I'm pretty sure AppVeyor has nuget in the path, but if there's a bug in the [bootstrap function](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/Private/Bootstrap-Nuget.ps1) on module load, that could slow things down.

Alternatively or additionally, it could be that when using PSGalleryModule, PowerShellGet [may be doing the same thing](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/PSDependScripts/PSGalleryModule.ps1#L115).

Things that might narrow it down:

* Displaying whether nuget is in path to double check
* Outside of and before PSDepend, run [this bit](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/PSDependScripts/PSGalleryModule.ps1#L115) in `measure-command`
* [This might also be expensive](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/PSDependScripts/PSGalleryModule.ps1#L149)
* If a module already exists, [this adds time](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/PSDependScripts/PSGalleryModule.ps1#L156)
* [PSGalleryNuget](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/PSDependScripts/PSGalleryNuget.ps1) might be slightly faster - it doesn't need to pull in existing modules, for example

Ick.  Forgot how ugly that code was : )

Cheers!

**Comment by gaelcolas** [comment]
Thanks @RamblingCookieMonster.
I haven't looked at the code much yet, but you're right about the time some of those takes.
Just to clarify, the issue is when running the test/Build locally as we're most likely up-to-date in our environment, and running the Build on CI is less time sensitive.
The current Build time for sample module is around 23 seconds locally and I found that on my system:
the `Get-Module -listAvaiable $moduleName` takes less than a couple of seconds, same for `Find-Module`. It's not much, but 4secs * 4 dependencies = 16 seconds delay before starting giving feedback.

The ultimate goal is to fail fast when running local, so that could be improved in different ways:
- Calling tasks conditionally
- Saving state to local file (i.e. when if you don't do a Clean)
- Improving the code in the dependency (in PSDepend)

For PSDepend, I suspect we could do something about it if we'd use Begin/Process/End type of structure, and then call the list of modules via the pipeline. This way we can do the `Get-Modules` for the list in the Begin block, and process the rest in-memory.

Optimisation is not yet the priority, so I left this as a note! Thanks again for pointing possible causes!

**Comment by gaelcolas** [comment]
[this is only in __Dev__ branch, not in master yet]

Kinda fixed/worked around this by changing how the dependencies are pulled (before the actual build tasks run), which allows to get rid of `.init.ps1` and have a unique point of entry for everything.
`.build.ps1`.
To pull dependencies use `./.build.ps1 -resolveDependency` but this is only required once per file change...
This is how a CI/CD tool should be configured (i.e. Appveyor).

When running locally, once you pulled things down, just run .build.ps1 and it's much quicker :)
